### PR TITLE
Feature/feature importance metrics

### PR DESCRIPTION
**Pull request by KilnOfTheSecondFlame**
## Drop and Relearn, Permute and Relearn Feature Importance Metrics

Added metrics from internal project, and added buttons for said metrics for Classification and Regression in `evaluate_model`.

## Type of change

Please delete options that are not relevant.
- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Made a small notebook to test for classification and regression

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA

## Checklist:
- [X] My code follows the style guidelines of this project.
- [X] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [X] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] New and existing unit tests pass locally with my changes.
- [X] Any dependent changes have been merged and published in downstream modules.

## Screenshots

image

### Classification
Feature Importance Classification (Permute and Relearn)

Feature Importance Classification (Drop and Relearn)

### Regression

Feature Importance Regression (Permute and Relearn)

Feature Importance Regression  (Drop and Relearn)

### CODE REVIEW

**Comment by andrinbuerli** [comment]
@KilnOfTheSecondFlame  title of permute and relearn plot is the same as the one of the generic feature importance plot, maybe you missed to push a commit?
image

**Comment by KilnOfTheSecondFlame** [comment]
@andrinbuerli But that's only for the generic FIM, for the new ones it should show up. But I can explicitely write (All) for the default one. A bug btw, the button is too small to show the full label:

image

**Comment by andrinbuerli** [comment]
@KilnOfTheSecondFlame Its not about the button. In the image I posted you see I selected the permutatino FIM and the title of the plot shows only "Feature importance plot", there I would expect  e.g. "Permutation feature importance plot"

**Comment by KilnOfTheSecondFlame** [comment]
> 
> 
> @KilnOfTheSecondFlame Its not about the button. In the image I posted you see I selected the permutatino FIM and the title of the plot shows only "Feature importance plot", there I would expect e.g. "Permutation feature importance plot"

No, you selected "Feature Importance (All)", the Permutation Plot is the next button down below

**Review by andrinbuerli — APPROVED** [review]

**Pull request merged**
